### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by callmesora**
### Updated readme with the following deppendencies and proper enviroment set up for gazebo simulation.

**TODO:** 
Add License to Read me

Há uma lista de ficheiros que necessitamos espalhados em 4 Repositorios, podem ver na parte "How to run". Por já deixo assim porque não sei que dependencias em especifico percisamos, mas eventualmente é melhor alterar aquilo de maneira a que esteja tudo no mesmo repo ou com as dependencias necessárias minimas.

### CODE REVIEW

**Comment by callmesora** [comment]
Podem dar preview do ReadMe no novo branch, apesar de ser coisa simples criei um branch novo e um pull request para a malta ir se habituando a Git Workflow mais metodica.

**Review by manuelgitgomes — COMMENTED** [review]
Hello! This is my first time doing a review on github, so if I am doing anything wrong, please correct me.
First of all, congrats on the great work, it's very well organized and explicit. I believe it's a wonderful addition to the project.
That being said, you have a few typos: 
- On line 18, "folliwing" should be "following";
- On line 41, "havent" should be "haven't";
- On line 63. "bhis" should be "this";
- On line 92, 98 and 136, "secound" should be "second";
You also have some lines with weird spacing between words.
You repeat the command on line 90 and line 96, I believe it should only be in one line, probably 96. 
Is there a way that I can change this file? If so, please tell me.
Again, thank you for the addition.

**Comment by callmesora** [comment]
> Hello! This is my first time doing a review on github, so if I am doing anything wrong, please correct me.
> First of all, congrats on the great work, it's very well organized and explicit. I believe it's a wonderful addition to the project.
> That being said, you have a few typos:
> 
> * On line 18, "folliwing" should be "following";
> * On line 41, "havent" should be "haven't";
> * On line 63. "bhis" should be "this";
> * On line 92, 98 and 136, "secound" should be "second";
>   You also have some lines with weird spacing between words.
>   You repeat the command on line 90 and line 96, I believe it should only be in one line, probably 96.
>   Is there a way that I can change this file? If so, please tell me.
>   Again, thank you for the addition.

Thanks I will fix them asap. 

Feel free to edit the files yourself if you want to.
First you have to pull the remote branch to your local branch.

1st
`git checkout -b readme` 
This will create a new branch called readme ( the name has to match the remote branch) and change your pointer to that branch automatically
2- 
`git pull`

You can check your branches by typing
`git branch`

**Comment by manuelgitgomes** [comment]
Ok, thank you! I will watch your lecture in the meantime!

**Pull request merged**
